# Generated by Django 4.2.7 on 2025-06-03 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagramcredentials',
            options={'verbose_name': 'Instagram Credentials', 'verbose_name_plural': 'Instagram Credentials'},
        ),
    ]
